Orange-OpenSource/a11y-guidelines

mobile/inputs/md/criteria-android-conception.md, mobile/inputs/md/criteria-ios-conception.md, mobile/inputs/md/index.md, web/inputs/md/fondamentaux-nontech.md, web/inputs/md/incontournables.md, web/inputs/md/incontournables/concepteurs/inc-con-orientation-ecran.md
- minor french typo ' =>’ ... =>… and some platform 
- minor space removing, md platform incompatibility
=> orientation Android and related homogenization

home/theme/default/js/reco.js, mobile/inputs/md/criteria-android-conception.md, mobile/inputs/md/criteria-android-dev.md
Changes in Android mobile and glossary, in french langage only. Kotlin exemples, updates for Android O, event sample link, orientation reco
=> Android update with Kotlin

src/fr/web/la-va11ydette/index.html, src/fr/web/la-va11ydette/js/lavallydette.js, src/fr/web/la-va11ydette/json/criteres-wcag-ease-en.json, src/fr/web/la-va11ydette/json/criteres-wcag-ease-fr.json, src/fr/web/la-va11ydette/json/lang/en.json, src/fr/web/la-va11ydette/json/lang/fr.json
URL to test : https://5f772b2218faa4000855ab40--a11y-guidelines-orange.netlify.app/fr/
=> Update the va11ydette

.eleventy.js, .github/workflows/main.yml, INSTALL.md, babel.config.json, netlify.toml, package-lock.json, package.json, postcss.config.js
Node is now supposed to be >= 14
=> Minify CSS & JS

src/en/web/toolbox/methods-and-test-tools/color-contrast-level.md, src/fr/web/outils/methodes-et-outils-de-test/mesurer-contraste-couleurs.md
- https://a11y-guidelines.orange.com/en/web/toolbox/methods-and-test-tools/color-contrast-level
- https://a11y-guidelines.orange.com/fr/web/outils/methodes-et-outils-de-test/mesurer-contraste-couleurs
=> fix(url): images had broken path

src/fr/mobile/android/conception/navigation-generale.md
Petite coquille remontée par Sébastien Delorme
=> Coquille navigation-generale.md

src/en/editorial-content/general.md, src/fr/contenu-editorial/generalites.md
j'ai mis à jour la page https://a11y-guidelines.orange.com/fr/contenu-editorial/generalites/ (version FR et EN) en réponse à l'issue #5 de @notabene
=> Maj editorial reco generales

src/_data/redirections.json
=> fix(urls): add missing redirection

src/en/web/toolbox/methods-and-test-tools/navigating-with-a-screen-reader.md, src/fr/web/outils/methodes-et-outils-de-test/navigation-lecteur-ecran.md
Add keyboard shortcut to start NVDA
=> Add NVDA shorcut

src/fr/web/la-va11ydette/js/lavallydette.js, src/fr/web/la-va11ydette/json/criteres-wcag-ease-en.json, src/fr/web/la-va11ydette/json/criteres-wcag-ease-fr.json, src/fr/web/la-va11ydette/json/lang/en.json, src/fr/web/la-va11ydette/json/lang/fr.json
- english version of last modified criterion (data table, colour information, sensorial information)
- update some missing traductions
=> vallydette english criterion update

src/_includes/components/header/main-navigation.njk, src/assets/style.css
- Update body links color (focus & hover)
- Change search icon color (orange -> white)
=> Update body links color

src/fr/web/la-va11ydette/js/lavallydette.js, src/fr/web/la-va11ydette/json/criteres-wcag-ease-en.json, src/fr/web/la-va11ydette/json/criteres-wcag-ease-fr.json, src/fr/web/la-va11ydette/json/lang/en.json, src/fr/web/la-va11ydette/json/lang/fr.json
- update criteria change of context, meaningful sequence, status messages
- open popin after create page
- add link to open a page url
- escape parenthesis for html attributes
=> update criteria change of context, meaningful sequence, status messages

src/fr/web/la-va11ydette/js/lavallydette.js, src/fr/web/la-va11ydette/json/issues-en.json, src/fr/web/la-va11ydette/json/issues-fr.json, src/fr/web/la-va11ydette/json/wcag-en.json, src/fr/web/la-va11ydette/json/wcag-fr.json
- add page badge in wcag no conformity list
- issues json localization
=> vallydette page badge function and issues localization

src/en/web/components-examples/dialogs/1/index.njk, src/en/web/components-examples/dialogs/1/script.js, src/en/web/components-examples/dialogs/2/script.js, src/en/web/components-examples/listbox-and-keyboard-navigation/index.njk, src/en/web/components-examples/listbox-and-keyboard-navigation/script.js, src/fr/web/exemples-de-composants/boites-de-dialogue/1/index.njk
Components english versions : 
- update dialogs articles with JS scripts versions
- update listbox and keyboard navigation with JS scripts versions
- update examples for both articles
=> update dialog and listbox component with JS scripts versions

src/fr/web/exemples-de-composants/bonnes-pratiques-pour-un-chatbot/index.njk, src/fr/web/exemples-de-composants/bonnes-pratiques-pour-un-chatbot/script.js
- script.js refactored from jQuery to JS
- update article examples
=> Chabot js version

src/en/web/components-examples/chatbot/index.njk, src/en/web/components-examples/chatbot/script.js
- script refactored from jQuery to JS
- update article example
=> script refactored from jQuery to JS

src/fr/web/exemples-de-composants/menu-deroulant/index.njk
- add some additionals informations (on aria-haspopup for example)
- replace role menu examples by a paragraph to explain the role menu specificities
=> update dropdown article

src/en/web/develop/keyboard-navigation.md, src/en/web/develop/layout.md, src/fr/articles/veille-mars-mai-2021.md, src/fr/web/developper/mise-en-page.md, src/fr/web/developper/navigation-clavier.md
mise à jour veille
et création critère "ordre de lecture compréhensible" dans mise en page et disparition dans nav clavier, ordre du focus
=> Ordrelecture

src/en/articles/watch-june-july-2021.md, src/fr/articles/veille-juin-juillet-2021.md
new file:   src/en/articles/watch-june-july-2021.md
new file:   src/fr/articles/veille-juin-juillet-2021.md
=> Veille fr/en juin juillet 21

src/fr/web/la-va11ydette/json/criteres-wcag-ease-en.json
A WCAG criterion was bad attributed
=> delete wcag 2.4.1 to structured heading

src/en/articles/watch-august-september-2021.md, src/en/articles/watch-june-july-2021.md, src/fr/articles/veille-aout-septembre-2021.md, src/fr/articles/veille-juin-juillet-2021.md
en et fr 
+ corrections précédente en et fr
=> Veille aout septembre

src/en/web/toolbox/methods-and-test-tools/navigating-with-a-screen-reader.md, src/fr/web/outils/methodes-et-outils-de-test/navigation-lecteur-ecran.md
Update of the procedure, because the indicated keyboard shortcut is no longer available in the latest versions of NVDA.
=> Update NVDA default configuration

src/en/articles/watch-december- january-2022.md, src/en/articles/watch-december-january-2022.md, src/fr/articles/veille-decembre-janvier-2022.md
changed file :
new file:   src/en/articles/watch-december- january-2022.md
new file:   src/fr/articles/veille-decembre-janvier-2022.md
=> Veille decembre-janvier 2022

src/en/articles/watch-october-november-2021.md, src/en/web/components-examples/forms/index.njk, src/en/web/components-examples/forms/script.js, src/fr/articles/veille-octobre-novembre-2021.md, src/fr/web/exemples-de-composants/formulaires/index.njk, src/fr/web/exemples-de-composants/formulaires/script.js
bon, premier jet de la page formulaire, pas mal de rajout
il reste des trucs à rajouter (exemple surtout et peut être du  contenu que j'aurais oublié)
j'ai entouré les endroits avec des  ---------------- là où j'ai besoin de vous...
et il y a  des choses sur lesquelles il faut kon statut
j'attends vos retour
=> Formulaire

src/en/digital-accessibility-definition.md, src/fr/definition-accessibilite-numerique.md
=> fix blockquote boosted 5

src/fr/articles/aria-live-alert.md, src/fr/contenu-et-communication/pdf.md
modified:   src/fr/articles/aria-live-alert.md
modified:   src/fr/contenu-et-communication/pdf.md
=> Changes to be committed:

src/en/web/components-examples/accessible-hiding/index.njk, src/fr/web/exemples-de-composants/masquage-accessible/index.njk
modified:   src/en/web/components-examples/accessible-hiding/index.njk
modified:   src/fr/web/exemples-de-composants/masquage-accessible/index.njk
=> modif composant "masquage accessible" fr/en

src/fr/articles/couleur-et-taille-du-texte.md
petite modif pour ajouter le fait de faire respectée ce critère selon une de ces conditions
- zoom texte
- zoom graphique
- zoom propre au site
=> Add zoom graphique

src/fr/articles/Carrousel.md
Hello,
Petite request pour l'article sur le Carrousel.
=> Add Carrousel

src/en/articles/watch-august-september-2022.md, src/fr/articles/veille-aout-septembre-2022.md, src/fr/articles/veille-template/veille-template.md
new file:   src/en/articles/watch-august-september-2022.md
new file:   src/fr/articles/veille-aout-septembre-2022.md
=> Veille aout - octobre 2022

src/fr/web/developper/contenu-textuel.md
modified:   src/fr/web/developper/contenu-textuel.md
=> corrections mineures critères

src/en/articles/watch-june-july-2023.md, src/fr/articles/veille-juin-juillet-2023.md
new file:   src/en/articles/watch-june-july-2023.md
new file:   src/fr/articles/veille-juin-juillet-2023.md
=> veille juin juillet On branch veille

src/en/articles/watch-august-september-2023.md, src/fr/articles/veille-aout-septembre-2023.md
new file:   src/en/articles/watch-august-september-2023.md
new file:   src/fr/articles/veille-aout-septembre-2023.md
=> Veille aout - septembre

src/en/articles/watch-october-november-2023.md, src/fr/articles/veille-octobre-novembre-2023.md
new file:   src/en/articles/watch-october-november-2023.md
new file:   src/fr/articles/veille-octobre-novembre-2023.md
=> veille oct-nov 23

src/en/mobile/ios/development.md, src/fr/mobile/ios/developpement.md
l'onglet SwiftUI pète l'affichage sur tout le reste de la page
=> Comment swiftui tab in reading order which leads to a broken display

src/en/articles/watch-december-january-2024.md, src/fr/articles/veille-decembre-janvier-2024.md
new file:   src/en/articles/watch-december-january-2024.md
new file:   src/fr/articles/veille-decembre-janvier-2024.md
=> veille dec*janv24

src/en/mobile/ios/development.md, src/fr/mobile/ios/developpement.md
The job is not completed about SwiftUI sections.
Some typography oad rendering issues remain, and several sections are empty.
This pull request brings more content for SwiftUI.
Closes #490
=> [#490] Fix some issues and add more samples for iOS with SwiftUI

src/en/articles/watch-april-may-2024.md, src/fr/articles/veille-avril-mai-2024.md, src/fr/articles/veille-fevrier-mars-2024.md
new file:   src/en/articles/watch-april-may-2024.md
new file:   src/fr/articles/veille-avril-mai-2024.md
=>  veille avril-mai 2024

src/_data/navigation.js
Improving the Accessiibility label in the footer.
=> Notabene patch 1 footer navigation

src/en/articles/watch-august-september-2024.md, src/fr/articles/veille-aout-septembre-2024.md
new file:   src/en/articles/watch-august-september-2024.md
new file:   src/fr/articles/veille-aout-septembre-2024.md
=> veille aout-september 2024

src/en/articles/watch-december-january-2025.md, src/fr/articles/veille-decembre-janvier-2025.md
new file:   src/en/articles/watch-december-january-2025.md
new file:   src/fr/articles/veille-decembre-janvier-2025.md
=> veille dec-janv 2025
